### PR TITLE
WIP: add ignore auth

### LINKED ISSUE #1: Support response cache even when request uses authentication
All my requests on API need authentication because it uses Client Credentials Flow. 

I've tried using the distributed caching with Redis on anonymous requests and I see Redis being hit.
When I use all my other authenticated requests, it uses cache but I don't see Redis being hit.

I'm using Swagger for making the requests, and if I authenticate on Swagger and call an anonymous request the Redis is not being hit also. 

Any idea of how can I still use distributed cache on authorized requests?

### PR DESCRIPTION
**Pull request by yringler**
will fix #1

### CODE REVIEW

**Comment by yringler** [comment]
@joaoantunes, this PR updates to netcore3, and lays some basic groundwork for #1.
The idea I'm going with for now is that all configure methods passed in to the middleware extensions will be of type `Action<CustomResponseCachingOptions>`, and the middleware in the constructor will accept an `ISnapShot<ResponseCachingOptions>`, which it will convert to `CustomResponseCachingOptions` to know which provider to use, and then pass in to the base `ResponseCacheMiddleware`.
I'm not %100 positive that ` ISnapShot<ResponseCachingOptions>` will be resolved from an instance of a child class, but it probably is. If not, we'll have to take `ISnapShot<CustomResponseCachingOptions>` and convert it to `ISnapShot<ResponseCachingOptions>` to pass it to the base middleware..

**Comment by yringler** [comment]
@joaoantunes, LMK if you want me to add you as a colaborator.

**Comment by joaoantunes** [comment]
I've seen that your implementation is a little different, this way will work too, but any specific reason why you are not using DI but manually creating the instances instead? 

This limit that those new classes won't be able to inject dependencies (ex.: logging), and the implementation for IResponseCachingPolicyProvider if is used elsewhere in the code, it will use the default ResponseCachingPolicyProvider.

You can add me, hope I can help :)

**Comment by yringler** [comment]
In aspnetcore a bunch of those classes which used to be public are now internal. Technically they can be DI'd, but being that it's not possible for another code base to override it anyway and that it's being used in a middeware and is therefor a singleton, there's no benefit to doing it that I'm aware of.
I tried to follow the pattern of the internal `ResponseCachingMiddleware`, which has a public constructor which accepts public DI parameters, and an internal constructor.
It's possible I made a mistake - I rushed it and haven't tested it. But that's the basic idea.

> This limit that those new classes won't be able to inject dependencies (ex.: logging),

I think all the middleware constructors take a logger in the constructor

> The implementation for IResponseCachingPolicyProvider if is used elsewhere in the code

It is only used within any ResponseCacheMIddlwares, which is why the core .Net doesn't bother DI'ing it either.

**Comment by yringler** [comment]
I would like for `ICustomResponseCache` to be public, but it's tricky because `IResponseCache` and `IResponseCacheEntry`.
If you have any ideas, by all means feel free.

**Comment by joaoantunes** [comment]
I'll work in a commit to demonstrating using DI and then you can decide if you want to use it.

But one issue of your approach is that for example now LocalCaching will not benefit from the implementation of the custom CacheAuthorizedRequestsResponseCachingPolicyProvider only the Distributed.

**Comment by yringler** [comment]
> now LocalCaching will not benefit

Note that the public constructor of the builtin `ResponseCache` (the one which the DI uses) does not receive an `IResponseCachingPolicyProvider`. It creates it itself and passes it in to the internal constructor, because as far as aspnetcore is concerned, there can only ever be one implementation because it's an internal interface.

If you do want to use `CacheAuthorizedRequestsResponseCachingPolicyProvider` with the builtin `ResponseCache`, there would have to be another middleware, which would internally use the builtin `ResponseCache`.

**Comment by yringler** [comment]
@joaoantunes , is your aspnetcore git submodule on version 3? I upgraded in my PR, which introduces the `internal` limitations (the price of progress). You would want to use/look at commit [f34272f1c0c903112c17bcb5a8a6b1a054e527f5 ](https://github.com/yringler/distributed-middleware-cache/pull/2/commits/f34272f1c0c903112c17bcb5a8a6b1a054e527f5)

**Comment by joaoantunes** [comment]
In my fork I have the old version, but I made a branch from this #2 👍

What I did:
- fixed some compile issues (missing usings)
- consolidate de versions 
- fixed the code regarding Authorize Caching (it was not working, because GetPolicy was not being able to provide the correct one, "cast" was failing)
- changed to choose the policy on the register (now uses DI) instead of a manual instance
- added a simple sample

**Comment by yringler** [comment]
It seems you haven't accepted my invitation to be a mantainer

**Comment by yringler** [comment]
As a fall back option, you could make a PR from your fork repo

**Comment by yringler** [comment]
The nuclear option would be to (after accepting the invitation)
1. clone with the git url (`git@github.com:yringler/distributed-middleware-cache.git`) which assuming you have an ssh/gpg key set up with your github account should work, then you can
1. get any branches from your fork and
1. push them here.

I'm sure there's a way to gracefully transition to using this repo, but it's outside of my git expertise to give advice in that regard.

**Comment by joaoantunes** [comment]
Ok I've accepted and was able to make PR.
You can check it here: #3 
If you have any doubts please tell me.

Do you have any idea why we can't use the Microsoft default extensions, it says it is ambiguous because we are using the hyperlink to those classes? Any idea how to fix this?

image

**Pull request merged**
